### ISSUE TITLE
Unable to view viedo. MediaSourceHandle error

### ISSUE THREAD

**Issue by DreamShaded** [mediacms-io/mediacms#516] opened 2022-09-02 03:21 UTC
**Describe the issue**
Hi, thx a lot for sush great product! Gotta issue with latest update. It is reproducing at the demo too. So for this moment all videos are unable to watch at latest docker deployment. I think it's only front-end error, but I've never worked with videojs, so maybe anyone will fix it faster.

Tried in incognito mode, without any extensions, too.

**To Reproduce**
Steps to reproduce the issue:
0. update to the latest docker image
1. Go to https://demo.mediacms.io/view?m=Pwc3NIWau  or your.domain/ 
2. Try to watch any uploaded video
3. See error at the browser console
4. Also there is no sources at video html tag, maybe this fact will be useful.

**Expected behavior**
Video have to be played

**Screenshots**
![2022-09-02_06-13](https://user-images.githubusercontent.com/52293645/188051814-2be602d0-d88d-4a7a-b2b3-e9e8a4cb91d0.png)

**Environment **
 - Browser: Google Chrome latest (105.0.5195.52 (Official Build) (64-bit)). 

**Additional context**
Also I've installed production version using docker-compose behind traefik, everything is okay except video playing, same at the project demo. Everything works in Firefox.

**Comment by DreamShaded** [comment] 2022-09-02 03:26
Oh, i got the solution! There is a [fresh issue](https://github.com/videojs/video.js/issues/7908) at VideoJS repo

**Comment by mgogoulos** [comment] 2022-09-02 07:18
Hi, thanks for reporting, this looks serious!

I cannot reproduce on the demo environment, I followed https://demo.mediacms.io/view?m=Pwc3NIWau through Chrome on Linux and I cannot reproduce. I'll try to check on other devices, but reading on the threads you mentioned it seems that video.js will need an update

**Comment by DreamShaded** [comment] 2022-09-02 09:14
@mgogoulos on the latest chrome? I use Ubuntu 22.04 with chrome 105.0.5195.52 (Official Build) (64-bit). Everything is ok from moble chrome and firefox, and was ok on the old chrome. I usually update once or twice a month, and today it ruined some things((

**Comment by Husky110** [comment] 2022-09-05 12:23
@mgogoulos - I can reproduce it with Chrome on Pop_OS. Maybe you need to hard-reload the site (using Ctrl + Shift + R) cause I don't think that MediaCMS uses Cache-busting...

**Comment by mgogoulos** [comment] 2022-09-07 09:35
I've just merged this PR: https://github.com/mediacms-io/mediacms/pull/519/files that updates video-js to latest stable version. The docker image will also be updated within the next few minutes. That issue should now be resolved, if you can checkout locally that would be great @Husky110 @DreamShaded ! 

Once again thanks all for reporting and helping troubleshoot!

**Closed by mgogoulos** 2022-09-07 09:35 UTC
Labels: bug, video

**Comment by Husky110** [comment] 2022-09-07 16:35
@mgogoulos - Hmm - I'm still having trouble with it. Have you updated dockerhub aswell? I tried redeploying my stack (docker-compose) through portainer and deleting (and pulling) the image beforehand, but it still seems to not work... In fact the code still uses `<script src="/static/lib/video-js/7.7.5/video.min.js"></script>` is there some cache I have to delete (or better should be deleted whenever a container is loaded)?

**Comment by Husky110** [comment] 2022-09-07 16:50
After checking a bit - there seems to be a serverside-cache that should be regenerated whenever the web-container starts.  
This is my docker-compose.yaml:  
`version: "3"

services:
  migrations:
    image: mediacms/mediacms:latest
    networks:
      - mediacms
    volumes:
      - mediacms-data:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: 'admin'
      ADMIN_EMAIL: 'my@e-mail.de'
      #ADMIN_PASSWORD: 'uncomment_and_set_password_here'
    command: "./deploy/docker/prestart.sh"
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  web:
    image: mediacms/mediacms:latest
    networks:
      - mediacms
    deploy:
      replicas: 1
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - mediacms-data:/home/mediacms.io/mediacms/
    environment:
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
  celery_beat:
    image: mediacms/mediacms:latest
    networks:
      - mediacms
    volumes:
      - mediacms-data:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - redis
  celery_worker:
    image: mediacms/mediacms:latest
    networks:
      - mediacms
    deploy:
      replicas: 1
    volumes:
      - mediacms-data:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
  db:
    image: postgres:13
    networks:
      - mediacms
    volumes:
      - mediacms-postgres:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: MYSUPERSECUREPASSWORD
      POSTGRES_DB: mediacms
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mediacms"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:alpine"
    restart: always
    networks:
      - mediacms
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mediacms:
    external: true

volumes:
  mediacms-postgres:
    external: true
  mediacms-data:
    external: true`
Everything in "mediacms-data" seems to be really static... Either move the static webfiles inside the container (cause I would thing that mediacms-data only holds my video-files and the config) or let the container regenerate them on startup.

**Comment by mgogoulos** [comment] 2022-09-08 08:18
Thanks, I'm going to update the docker configuration soon. Make sure you `git pull` in your local installation and that you get the new Docker image, it includes the updated version

**Comment by Husky110** [comment] 2022-09-08 09:06
@mgogoulos - normally, doing the `git pull` is the containers job... :) but thanks anyhow.

**Comment by Husky110** [comment] 2022-09-08 09:22
`git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
`

**Comment by WhiskeyCoder** [comment] 2025-01-12 14:20
@Husky110 Hey just seen your comments I have been trying to get this up and running on my portainer on my homelab, keep getting missing sh scripts when trying to build. Did you happen to get this working and or happen to have a stack file that I try to get it working on my side??

**Comment by Husky110** [comment] 2025-01-20 17:17
Hey @WhiskeyCoder - Sorry, but I don't use this tool anymore and when you wrote I was on vaccation. Sorry to disappoint you here. :(

**Comment by WhiskeyCoder** [comment] 2025-01-20 17:36
> Hey [@WhiskeyCoder](https://github.com/WhiskeyCoder) - Sorry, but I don't use this tool anymore and when you wrote I was on vaccation. Sorry to disappoint you here. :(

It's cool, pity, thanks for the reply anyway
